trigger: none

variables:
  - name: skipComponentGovernanceDetection
    value: true
  - name: vmImageName
    value: ubuntu-latest
  - name: LinuxContainerImage
    value: 'onebranch.azurecr.io/linux/ubuntu-2004:latest'
name: '$(date:yyyyMMdd)$(rev:.r)'

resources:
  repositories:
    - repository: onebranchTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@onebranchTemplates
  parameters:
    customTags: ES365AIMigrationTooling
    stages:
      - stage: stage
        jobs:
          - job: Phase_1
            displayName: Build
            cancelTimeoutInMinutes: 1
            pool:
              type: linux
            variables:
              - name: ob_outputDirectory
                value: $(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT
            steps:
              - task: NodeTool@0
                displayName: Use Node Version 12.x
                inputs:
                  versionSpec: 12.x
                  checkLatest: true
              - task: Npm@1
                displayName: Install Dependencies
                inputs:
                  command: install
              - task: Npm@1
                displayName: Build Project
                inputs:
                  command: custom
                  customCommand: run build
