name: Build-and-Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '10.16.3'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish SDK
        run: cd apps/pagetour-sdk && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish LocalRepository
        run: cd apps/pagetour-sdk.localrepository && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish HttpRepository
        run: cd apps/pagetour-sdk.httprepository && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
