name: Build-and-Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Setup Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '10.16.3'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish SDK
        run: cd apps/pagetour-sdk && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish LocalRepository
        run: cd apps/pagetour-sdk.localrepository && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish HttpRepository
        run: cd apps/pagetour-sdk.httprepository && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
