name: Gated Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependancies
        run: npm install
      - name: Build
        run: npm run build
      - name: Install dependancies from registery
        run: cd apps/sample && npm install
